enableInlineBuilds: true
enableTimers: false
enableProgressBars: false
nodeLinker: node-modules

logFilters:
  - code: YN0000
    level: discard
  - code: YN0013
    level: discard
  - code: "YN0002"
    level: discard
  - code: "YN0060"
    level: discard
  - text: "Resolution step"
    level: discard
  - text: "Fetch step"
    level: discard
  - text: "Link step"
    level: discard

supportedArchitectures:
  os: ['darwin', 'linux']
  cpu: ['x64', 'arm64']
