<?php

require BASE_DIR . '/src/Assistant/Module/Common/Resources/routes/default.inc';
require BASE_DIR . '/src/Assistant/Module/Dashboard/Resources/routes/default.inc';
require BASE_DIR . '/src/Assistant/Module/Directory/Resources/routes/default.inc';
require BASE_DIR . '/src/Assistant/Module/Mix/Resources/routes/default.inc';
require BASE_DIR . '/src/Assistant/Module/Search/Resources/routes/default.inc';
require BASE_DIR . '/src/Assistant/Module/Track/Resources/routes/default.inc';
